version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez data
    tables:
      - name: products
        identifier: raw_gz_product
        description: products list
        columns:
          - name: products_id
          - name: purchSE_PRICE
      - name: sales
        identifier: raw_gz_sales
        description: sales list
        freshness: 
          warn_after:
            count: 85
            period: day
          error_after:
            count: 90
            period: day
        loaded_at_field: date_date
        
        columns:
          - name: sales_id
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity
      - name: ship
        identifier: raw_gz_ship
        description: ship list
        columns:
          - name: orders_id
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost

models:
  - name: stg_raw__products
    columns:
      - name: products_id
        tests:
          - unique
          - not_null
      - name: purchase_price
  - name: stg_raw__sales
    columns:
          - name: sales_id
            tests:
              - unique
              - not_null
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity
  - name: stg_raw__ship
    columns:
          - name: orders_id
            tests:
              - unique
              - not_null
          - name: shipping_fee
          - name: logCost
          - name: ship_cost

